In [40]:
import pandas as pd
import numpy as np

In [41]:
data=pd.read_csv("./data/Student_Marks.csv")

In [42]:
data

number_courses  time_study   Marks
0                3       4.508  19.202
1                4       0.096   7.734
2                4       3.133  13.811
3                6       7.909  53.018
4                8       7.811  55.299
..             ...         ...     ...
95               6       3.561  19.128
96               3       0.301   5.609
97               4       7.163  41.444
98               7       0.309  12.027
99               3       6.335  32.357

[100 rows x 3 columns]

In [43]:
x = data.drop(labels=["Marks"],axis=1)

In [44]:
x

number_courses  time_study
0                3       4.508
1                4       0.096
2                4       3.133
3                6       7.909
4                8       7.811
..             ...         ...
95               6       3.561
96               3       0.301
97               4       7.163
98               7       0.309
99               3       6.335

[100 rows x 2 columns]

In [45]:
y = data[["Marks"]]

In [46]:
y

Marks
0   19.202
1    7.734
2   13.811
3   53.018
4   55.299
..     ...
95  19.128
96   5.609
97  41.444
98  12.027
99  32.357

[100 rows x 1 columns]

In [47]:
categorical_column = x.select_dtypes(include="object").columns

In [48]:
categorical_column

Index([], dtype='object')

In [49]:
numerical_columns = x.select_dtypes(exclude="object").columns

In [50]:
numerical_columns

Index(['number_courses', 'time_study'], dtype='object')

In [51]:
data["number_courses"].unique()

array([3, 4, 6, 8, 5, 7], dtype=int64)

In [52]:
data["time_study"].unique()

array([4.508, 0.096, 3.133, 7.909, 7.811, 3.211, 6.063, 3.413, 4.41 ,
       6.173, 7.353, 0.423, 4.218, 4.274, 2.908, 4.26 , 5.719, 6.08 ,
       7.711, 3.977, 4.733, 6.126, 2.051, 4.875, 3.635, 1.407, 0.508,
       4.378, 0.156, 1.299, 3.864, 1.923, 0.932, 6.594, 4.083, 7.543,
       2.966, 7.283, 6.533, 7.775, 0.14 , 2.754, 3.591, 1.557, 1.954,
       2.061, 3.797, 4.779, 5.635, 3.913, 6.703, 4.13 , 0.771, 6.049,
       7.591, 2.913, 7.641, 7.649, 6.198, 7.468, 0.376, 2.438, 3.606,
       4.869, 0.13 , 2.142, 5.473, 0.55 , 1.395, 3.948, 3.736, 2.518,
       4.633, 1.629, 6.954, 0.803, 6.379, 5.985, 7.451, 0.805, 7.957,
       2.262, 7.41 , 3.197, 1.982, 6.201, 4.067, 1.033, 1.803, 6.376,
       4.182, 2.73 , 5.027, 6.471, 3.919, 3.561, 0.301, 7.163, 0.309,
       6.335])

In [53]:
data["Marks"].unique().min()

5.609

In [54]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OrdinalEncoder

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [55]:
num_pipeline = Pipeline(
steps=[
    ("imputer",SimpleImputer()),
    ("Scaler",StandardScaler())
]

)

In [56]:
cat_pipeline = Pipeline(
steps=[
    ("imputer",SimpleImputer()),
    ("ordinalencoder",OrdinalEncoder())
]
)

In [57]:
prepocessor = ColumnTransformer(
[
    ("num_pipeline",num_pipeline,numerical_columns),
    ("cat_pipeline",cat_pipeline,categorical_column)
]
)

In [58]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=42)

In [59]:
x_train

number_courses  time_study
55               7       2.913
88               5       1.803
26               7       0.508
42               6       3.591
69               6       3.948
..             ...         ...
60               6       0.376
71               5       2.518
14               3       2.908
92               4       5.027
51               6       4.130

[80 rows x 2 columns]

In [60]:
y_train

Marks
55  18.238
88  11.253
26  12.647
42  19.771
69  21.400
..     ...
60  10.522
71  13.416
14  11.397
92  23.916
51  22.184

[80 rows x 1 columns]

In [61]:
prepocessor.fit_transform(x_train)

array([[ 0.97226573, -0.41235382],
       [-0.14688907, -0.88339102],
       [ 0.97226573, -1.43293443],
       [ 0.41268833, -0.1246392 ],
       [ 0.41268833,  0.02685655],
       [-0.70646647,  0.15925619],
       [-0.70646647, -1.58909811],
       [-1.26604386, -1.5207765 ],
       [-1.26604386,  0.97105274],
       [-1.26604386,  0.31754167],
       [ 0.97226573, -1.46900484],
       [-0.70646647,  0.37949791],
       [ 1.53184313,  0.98293476],
       [-0.14688907, -1.58230839],
       [ 1.53184313,  1.09751138],
       [ 0.41268833, -0.28589518],
       [-0.70646647,  0.67400225],
       [ 0.41268833, -0.73953371],
       [-1.26604386,  1.55242299],
       [-0.14688907,  0.77839428],
       [-0.14688907,  0.01200402],
       [-1.26604386,  0.08414486],
       [-0.14688907, -0.2001749 ],
       [ 0.41268833, -0.13736994],
       [ 1.53184313,  0.20933042],
       [ 1.53184313,  0.03916292],
       [ 1.53184313, -0.68861077],
       [-1.26604386, -1.05143673],
       [ 0.41268833,

In [62]:
prepocessor.transform(x_test)

array([[-0.14688907, -0.29183619],
       [ 0.97226573,  0.91843237],
       [-0.70646647, -0.06310732],
       [-1.26604386, -0.7739067 ],
       [-0.70646647, -0.81931299],
       [ 0.41268833,  1.650874  ],
       [-0.14688907, -0.77815028],
       [ 0.97226573,  1.72810713],
       [-1.26604386,  1.471795  ],
       [-1.26604386,  0.26449694],
       [ 0.41268833,  1.6237151 ],
       [ 1.53184313, -0.00878951],
       [-1.26604386, -0.95722929],
       [ 0.41268833,  1.14970739],
       [ 0.97226573,  0.12615628],
       [ 1.53184313,  1.66615089],
       [-0.14688907,  1.05847046],
       [ 1.53184313,  0.89127347],
       [ 0.97226573,  0.14143316],
       [-1.26604386, -0.83246808]])

In [63]:
prepocessor.get_feature_names_out()

array(['num_pipeline__number_courses', 'num_pipeline__time_study'],
      dtype=object)

In [64]:
x_train = pd.DataFrame(prepocessor.fit_transform(x_train),columns=prepocessor.get_feature_names_out())

In [65]:
x_train

num_pipeline__number_courses  num_pipeline__time_study
0                       0.972266                 -0.412354
1                      -0.146889                 -0.883391
2                       0.972266                 -1.432934
3                       0.412688                 -0.124639
4                       0.412688                  0.026857
..                           ...                       ...
75                      0.412688                 -1.488950
76                     -0.146889                 -0.579975
77                     -1.266044                 -0.414476
78                     -0.706466                  0.484739
79                      0.412688                  0.104090

[80 rows x 2 columns]

In [66]:
x_test = pd.DataFrame(prepocessor.fit_transform(x_test),columns=prepocessor.get_feature_names_out())

In [67]:
x_test

num_pipeline__number_courses  num_pipeline__time_study
0                      -0.222222                 -0.743878
1                       0.888889                  0.542021
2                      -0.777778                 -0.500856
3                      -1.333333                 -1.256073
4                      -0.777778                 -1.304316
5                       0.333333                  1.320232
6                      -0.222222                 -1.260582
7                       0.888889                  1.402292
8                      -1.333333                  1.129963
9                      -1.333333                 -0.152779
10                      0.333333                  1.291376
11                      1.444444                 -0.443143
12                     -1.333333                 -1.450851
13                      0.333333                  0.787748
14                      0.888889                 -0.299765
15                      1.444444                  1.336464
16                     -0.222222                  0.690810
17                      1.444444                  0.513164
18                      0.888889                 -0.283533
19                     -1.333333                 -1.318294

In [68]:
from sklearn.linear_model import LinearRegression,Ridge,ElasticNet,Lasso
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [69]:
def evaluate_model(true,prediction):
    r2_square = r2_score(true,prediction),
    mae = mean_absolute_error(true,prediction),
    mse = mean_squared_error(true,prediction)
    return r2_square,mae,mse

In [70]:
models = {
    "LinearRegression":LinearRegression(),
    "Ridge":Ridge(),
    "ElasticNet":ElasticNet(),
    "Lasso":Lasso()
}

In [71]:
models.keys()

dict_keys(['LinearRegression', 'Ridge', 'ElasticNet', 'Lasso'])

In [72]:
list(models.values())

[LinearRegression(), Ridge(), ElasticNet(), Lasso()]

In [73]:
list(models)

['LinearRegression', 'Ridge', 'ElasticNet', 'Lasso']

In [74]:
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(x_train,y_train)
    
    y_pred = model.predict(x_test)
    r2_square,mae,mse=evaluate_model(y_test,y_pred)
    
    print(list(models.keys())[i])
    print("...Our Result...")
    print("r2_square :",r2_square)
    print("mean_absolute_error :",mae)
    print("mean_squared_error :",mse)
    print("-"*35)
    print("\n")

LinearRegression
...Our Result...
r2_square : (0.8447348792728553,)
mean_absolute_error : (5.491200000000001,)
mean_squared_error : 40.826232977079485
-----------------------------------


Ridge
...Our Result...
r2_square : (0.8422897290410032,)
mean_absolute_error : (5.4912,)
mean_squared_error : 41.46917372618039
-----------------------------------


ElasticNet
...Our Result...
r2_square : (0.6833506877753004,)
mean_absolute_error : (6.406631115946484,)
mean_squared_error : 83.26144682317859
-----------------------------------


Lasso
...Our Result...
r2_square : (0.820952482032379,)
mean_absolute_error : (5.4912,)
mean_squared_error : 47.079702435937705
-----------------------------------


